[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Familiar badges
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = "if AUT.badges then"
position = 'before'
match_indent = true
payload = '''
if Object.is(card, Card) then
  if card:has_attribute("tboj_angel") then
    badges[#badges+1] = create_badge(localize("tboj_angel"), G.C.TBOJ.ANGEL, G.C.WHITE )
  end
  if card:has_attribute("tboj_book") then
    badges[#badges+1] = create_badge(localize("tboj_book"), G.C.TBOJ.BOOK, G.C.WHITE )
  end
  if card:has_attribute("tboj_devil") then
    badges[#badges+1] = create_badge(localize("tboj_devil"), G.C.TBOJ.DEVIL, G.C.WHITE )
  end
  if card:has_attribute("tboj_familiar") then
    badges[#badges+1] = create_badge(localize("tboj_familiar"), G.C.TBOJ.FAMILIAR, G.C.WHITE )
  end
  --if card:has_attribute("tboj_fly") then
  --  badges[#badges+1] = create_badge(localize("tboj_fly"), G.C.TBOJ.FLY, G.C.WHITE )
  --end
  if card:has_attribute("tboj_guppy") then
    badges[#badges+1] = create_badge(localize("tboj_guppy"), G.C.TBOJ.GUPPY, G.C.WHITE )
  end
  --if card:has_attribute("tboj_poop") then
  --  badges[#badges+1] = create_badge(localize("tboj_poop"), G.C.TBOJ.POOP, G.C.WHITE )
  --end
end
'''

# Active rarity badges
#[[patches]]
#[patches.pattern]
#target = 'functions/UI_definitions.lua'
#pattern = "if AUT.card_type == 'Joker' or (AUT.badges and AUT.badges.force_rarity) then card_type = SMODS.Rarity:get_rarity_badge(card.config.center.rarity) end"
#position = 'after'
#match_indent = true
#payload = '''
#if AUT.card_type == 'tboj_Active' then card_type = SMODS.Rarity:get_rarity_badge(card.config.center.rarity) end
#'''