[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Thanks Emma for the following 3 patches
# end_round / new_round
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "if G.GAME.round_resets.blind == G.P_BLINDS.bl_small then"
position = "at"
match_indent = true
payload = "if G.GAME.round_resets.blind_states.Small == 'Current' then"
times = 2

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "elseif G.GAME.round_resets.blind == G.P_BLINDS.bl_big then"
position = "at"
match_indent = true
payload = "elseif G.GAME.round_resets.blind_states.Big == 'Current' then"
times = 2

# ease_background_colour_blind
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if v.boss.showdown then"
position = "at"
payload = "if v.boss and v.boss.showdown then"
match_indent = true