[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# pre_splash context
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = "G.GAME.hands[text].visible = true"
position = 'after'
match_indent = true
payload = '''
SMODS.calculate_context({pre_splash = true, full_hand = G.play.cards, scoring_hand = scoring_hand, in_scoring = true, ignore_other_debuff = true}, effects)
'''

# determine_hand context
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = "local text,disp_text,poker_hands,scoring_hand,non_loc_disp_text = G.FUNCS.get_poker_hand_info(G.play.cards)"
position = 'before'
match_indent = true
payload = '''
SMODS.calculate_context({determine_hand = true, full_hand = G.play.cards, scoring_hand = scoring_hand, in_scoring = true, ignore_other_debuff = true}, effects)
'''