# Credit to @MathIsFun_ for creating TheOrder, which this integration is a copy of
[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Patches boss generation to be ante-based
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "local _, boss = pseudorandom_element(eligible_bosses, pseudoseed('boss'))"
position = "at"
payload = '''local boss = nil
if MP.should_use_the_order() then
	_, boss = pseudorandom_element(eligible_bosses, pseudoseed('boss'..G.GAME.round_resets.ante))
else
	_, boss = pseudorandom_element(eligible_bosses, pseudoseed('boss'))
end'''
match_indent = true

# Adds an asterisk to the front of the seed
# This isn't required for the mod to function, but it makes it easier to identify that seeds vary from vanilla
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "for k, v in pairs(self.GAME.pseudorandom) do if v == 0 then self.GAME.pseudorandom[k] = pseudohash(k..self.GAME.pseudorandom.seed) end end"
position = "before"
payload = '''if self.GAME.pseudorandom.seed:sub(1, 1) ~= "*" and MP.should_use_the_order() then self.GAME.pseudorandom.seed = "*" .. self.GAME.pseudorandom.seed end'''
match_indent = true

# Ankh compat w/ previous patch
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "self.GAME.pseudorandom.seed = hash_seed(self.GAME.pseudorandom.seed)"
position = "before"
payload = '''if self.GAME.pseudorandom.seed:sub(1, 1) ~= "*" and MP.should_use_the_order() then self.GAME.pseudorandom.seed = "*" .. self.GAME.pseudorandom.seed end'''
match_indent = true




# Make hallucination coinflip queue global
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if SMODS.pseudorandom_probability(self, 'halu'..G.GAME.round_resets.ante, 1, self.ability.extra) then'''
position = "at"
payload = '''if SMODS.pseudorandom_probability(self, 'halu'..MP.ante_based(), 1, self.ability.extra) then'''
match_indent = true

# Make booster pack queue global
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/overrides.lua"]'''
pattern = '''local poll = pseudorandom(pseudoseed((_key or 'pack_generic')..G.GAME.round_resets.ante))*cume'''
position = "at"
payload = '''local poll = pseudorandom(pseudoseed((_key or 'pack_generic')..MP.ante_based()))*cume'''
match_indent = true

# Make deck shuffles round based
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''G.deck:shuffle('nr'..G.GAME.round_resets.ante)'''
position = "at"
payload = '''G.deck:shuffle('nr'..MP.order_round_based(true))'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''G.deck:shuffle('cashout'..G.GAME.round_resets.ante)'''
position = "at"
payload = '''G.deck:shuffle('cashout'..MP.order_round_based(true))'''
match_indent = true

# Patch polled rate
# This determines whether shop card is tarot/joker/planet/etc
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''local polled_rate = pseudorandom(pseudoseed('cdt'..G.GAME.round_resets.ante))*total_rate'''
position = "at"
payload = '''local polled_rate = pseudorandom(pseudoseed('cdt'..MP.ante_based()))*total_rate'''
match_indent = true

# Resample advances queue instead of rerolling
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''center = pseudorandom_element(_pool, pseudoseed(_pool_key..'_resample'..it))'''
position = "at"
payload = '''
center = pseudorandom_element(_pool, pseudoseed(_pool_key..(MP.should_use_the_order() and '' or ('_resample'..it)) ))
if MP.should_use_the_order() and it > 1000 then -- fallback
	center = pseudorandom_element(_pool, pseudoseed(_pool_key..'_resample'..it))
end
'''
match_indent = true

# stable shop
# select rarity, then that rarity's stickers, then the joker from either normal or stickered queue
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''if forced_key and not G.GAME.banned_keys[forced_key] then'''
position = "before"
payload = '''
local _order_et, _order_per, _order_rent, _order_ed = nil, nil, nil, nil
if _type == "Joker" and not forced_key and MP.should_use_the_order() then
	local _pool, _pool_key = get_current_pool(_type, _rarity, legendary, key_append)
	forced_key = "UNAVAILABLE"
	local it = 0
	while forced_key == "UNAVAILABLE" do
		_order_et, _order_per, _order_rent, _order_ed = nil, nil, nil, nil
		-- select stickers based off of rarity
		if (area == G.pack_cards) or (area == G.shop_jokers) then
			local eternal_perishable_poll = pseudorandom("_etper".._pool_key)

			-- block of nonsense
			if G.GAME.modifiers.enable_eternals_in_shop
			and eternal_perishable_poll > 0.7
			and not SMODS.Stickers["eternal"].should_apply then
				_order_et = true
			elseif G.GAME.modifiers.enable_perishables_in_shop
			and ((eternal_perishable_poll > 0.4)
			and (eternal_perishable_poll <= 0.7))
			and not SMODS.Stickers["perishable"].should_apply then
				_order_per = true
			end
			if G.GAME.modifiers.enable_rentals_in_shop
			and pseudorandom("_rent".._pool_key) > 0.7
			and not SMODS.Stickers["rental"].should_apply then
				_order_rent = true
			end
		end

		local _s_append = ""
		if _order_et or _order_per or _order_rent then
			_s_append = "_sticker"
		end
		forced_key = pseudorandom_element(_pool, pseudoseed(_pool_key.._s_append))
		if it > 1000 then -- fallback
			forced_key = pseudorandom_element(_pool, pseudoseed(_pool_key.._s_append..'_resample'..it))
		end
		if forced_key ~= "UNAVAILABLE" then
			-- breaking news. this mutates the `_pool` (IT'S NOT LOCAL)
			-- so only do it when you're done (IT'S NOT LOCAL)
			-- we'll need to advance the rng queue silently (THE VARIABLE POINTS TO A GLOBAL)
			_order_ed = poll_edition('edi'.._pool_key.._s_append)
		else
			-- advance said rng queue silently
			pseudorandom(pseudoseed('edi'.._pool_key.._s_append))
		end
		it = it + 1
	end
end
'''
match_indent = true

# override vanilla sticker and edition setting with the previously defined stickers and editions
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''if (area == G.shop_jokers) or (area == G.pack_cards) then'''
position = "before"
payload = '''
if MP.should_use_the_order() then
	if _order_et then card:set_eternal(_order_et) end
	if _order_per then card:set_perishable(_order_per) end
	if _order_rent then card:set_rental(_order_rent) end
	card:set_edition(_order_ed)
	-- wow what a suspiciously dangerously placed return that prevents any code below it from running!
	-- i sure hope this doesn't cause any problems whatsoever
	return card
end
'''
match_indent = true

# Patch To-Do List rng to be the same on different operating systems
# This is a vanilla bug!
# Orbital adjacent fix is in ui/game.lua
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''while not self.ability.to_do_poker_hand do'''
position = "before"
payload = '''
if MP.should_use_the_order() then
	_poker_hands = MP.sorted_hand_list(self.ability.to_do_poker_hand)
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''self.ability.to_do_poker_hand = pseudorandom_element(_poker_hands, pseudoseed('to_do'))'''
position = "before"
payload = '''
if MP.should_use_the_order() then
	_poker_hands = MP.sorted_hand_list(self.ability.to_do_poker_hand)
end
'''
match_indent = true

# STEAMODDED BUG - fix for certificate calling pseudorandom for no reason
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils.lua"]'''
pattern = '''
local seal_poll = pseudorandom(pseudoseed(key or 'stdseal'..G.GAME.round_resets.ante))
if seal_poll > 1 - (type_weight*mod / total_weight) or guaranteed then -- is a seal generated
'''
position = 'at'
payload = '''
local seal_poll = guaranteed and 1 or pseudorandom(pseudoseed(key or 'stdseal'..G.GAME.round_resets.ante))
if seal_poll > 1 - (type_weight*mod / total_weight) then -- is a seal generated
'''
match_indent = true
times = 1