[manifest]
version = "1.0.0"
dump_lua = true
priority = 2147483600

# Force gamespeed to vanilla 4x when we need to
[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = 'self.TIMERS.TOTAL = self.TIMERS.TOTAL + dt*(self.SPEEDFACTOR)'
position = 'before'
payload = '''
if MP.TIMER_FORCE_GAMESPEED and (G.STAGE == G.STAGES.RUN and not G.SETTINGS.paused and not G.screenwipe) then
    self.SPEEDFACTOR = math.max(self.SPEEDFACTOR, 4 + math.max(0, math.abs(G.ACC) - 2))
end
'''
times = 1
match_indent = true
