-- Auto-generated ruleset shape snapshot. Do not edit.
-- Regenerate with: lua tests/test_ruleset_shape.lua capture
return {
  ["badlatro"] = {
    ["_has_functions"] = {
      ["create_info_menu"] = true,
      ["force_lobby_options"] = true,
      ["is_disabled"] = true,
    },
    ["banned_blinds"] = {},
    ["banned_consumables"] = {
      "c_deja_vu",
      "c_justice",
      "c_trance",
    },
    ["banned_enhancements"] = {
      "m_glass",
    },
    ["banned_jokers"] = {
      "j_abstract",
      "j_acrobat",
      "j_ancient",
      "j_arrowhead",
      "j_baron",
      "j_baseball",
      "j_bloodstone",
      "j_blue_joker",
      "j_blueprint",
      "j_brainstorm",
      "j_caino",
      "j_card_sharp",
      "j_cartomancer",
      "j_cavendish",
      "j_certificate",
      "j_dna",
      "j_dusk",
      "j_family",
      "j_fibonacci",
      "j_hanging_chad",
      "j_hologram",
      "j_loyalty_card",
      "j_lucky_cat",
      "j_mail",
      "j_midas_mask",
      "j_mime",
      "j_mp_defensive_joker",
      "j_onyx_agate",
      "j_perkeo",
      "j_photograph",
      "j_reserved_parking",
      "j_selzer",
      "j_steel_joker",
      "j_trading",
      "j_triboulet",
      "j_trio",
      "j_vagabond",
      "j_yorick",
    },
    ["banned_tags"] = {
      "tag_garbage",
      "tag_handy",
      "tag_meteor",
      "tag_top_up",
      "tag_uncommon",
    },
    ["banned_vouchers"] = {
      "v_magic_trick",
    },
    ["key"] = "badlatro",
    ["multiplayer_content"] = true,
    ["reworked_blinds"] = {},
    ["reworked_consumables"] = {},
    ["reworked_enhancements"] = {},
    ["reworked_jokers"] = {},
    ["reworked_tags"] = {},
    ["reworked_vouchers"] = {},
    ["spectral_banned_enhancements"] = {
      "m_glass",
    },
  },
  ["blitz"] = {
    ["_has_functions"] = {
      ["create_info_menu"] = true,
      ["force_lobby_options"] = true,
      ["is_disabled"] = true,
    },
    ["banned_blinds"] = {},
    ["banned_consumables"] = {
      "c_justice",
    },
    ["banned_enhancements"] = {},
    ["banned_jokers"] = {},
    ["banned_silent"] = {
      "c_ouija",
      "j_bloodstone",
      "j_hanging_chad",
      "j_selzer",
      "j_ticket",
      "j_turtle_bean",
    },
    ["banned_tags"] = {},
    ["banned_vouchers"] = {},
    ["key"] = "blitz",
    ["multiplayer_content"] = true,
    ["reworked_blinds"] = {},
    ["reworked_consumables"] = {
      "c_mp_ouija_standard",
    },
    ["reworked_enhancements"] = {
      "m_glass",
    },
    ["reworked_jokers"] = {
      "j_mp_bloodstone",
      "j_mp_hanging_chad",
      "j_mp_seltzer",
      "j_mp_ticket",
      "j_mp_turtle_bean",
    },
    ["reworked_tags"] = {},
    ["reworked_vouchers"] = {},
    ["spectral_banned_enhancements"] = {},
    ["standard"] = true,
  },
  ["chaos"] = {
    ["_has_functions"] = {
      ["create_info_menu"] = true,
      ["force_lobby_options"] = true,
      ["is_disabled"] = true,
    },
    ["banned_blinds"] = {},
    ["banned_consumables"] = {
      "c_ectoplasm",
      "c_justice",
      "c_ouija",
    },
    ["banned_enhancements"] = {},
    ["banned_jokers"] = {
      "j_hanging_chad",
    },
    ["banned_silent"] = {
      "c_ouija",
      "j_baseball",
      "j_bloodstone",
      "j_castle",
      "j_hanging_chad",
      "j_hit_the_road",
      "j_idol",
      "j_mail",
      "j_misprint",
      "j_selzer",
      "j_square",
      "j_steel_joker",
      "j_throwback",
      "j_ticket",
      "j_ticket",
      "j_turtle_bean",
      "j_vampire",
    },
    ["banned_tags"] = {
      "tag_investment",
      "tag_juggle",
      "tag_rare",
    },
    ["banned_vouchers"] = {},
    ["key"] = "chaos",
    ["multiplayer_content"] = true,
    ["reworked_blinds"] = {},
    ["reworked_consumables"] = {
      "c_mp_ectoplasm_sandbox",
      "c_mp_ouija_standard",
      "c_mp_ouija_standard",
    },
    ["reworked_enhancements"] = {
      "m_glass",
      "m_glass",
    },
    ["reworked_jokers"] = {
      "j_mp_alloy_sandbox",
      "j_mp_ambrosia_sandbox",
      "j_mp_bloodstone",
      "j_mp_bobby_sandbox",
      "j_mp_candynecklace_sandbox",
      "j_mp_chainlightning_sandbox",
      "j_mp_clowncar_sandbox",
      "j_mp_clowncollege_sandbox",
      "j_mp_couponsheet_sandbox",
      "j_mp_doublerainbow_sandbox",
      "j_mp_error_sandbox_1",
      "j_mp_error_sandbox_10",
      "j_mp_error_sandbox_11",
      "j_mp_error_sandbox_12",
      "j_mp_error_sandbox_13",
      "j_mp_error_sandbox_14",
      "j_mp_error_sandbox_2",
      "j_mp_error_sandbox_3",
      "j_mp_error_sandbox_4",
      "j_mp_error_sandbox_5",
      "j_mp_error_sandbox_6",
      "j_mp_error_sandbox_7",
      "j_mp_error_sandbox_8",
      "j_mp_error_sandbox_9",
      "j_mp_espresso_sandbox",
      "j_mp_farmer_sandbox",
      "j_mp_forklift_sandbox",
      "j_mp_gofish_sandbox",
      "j_mp_hanging_chad",
      "j_mp_hanging_chad",
      "j_mp_hoarder_sandbox",
      "j_mp_idol_sandbox_collector",
      "j_mp_idol_sandbox_zealot",
      "j_mp_jokalisa_sandbox",
      "j_mp_jokeroftheyear_sandbox",
      "j_mp_lucky7_sandbox",
      "j_mp_montehaul_sandbox",
      "j_mp_pocketaces_sandbox",
      "j_mp_pyromancer_sandbox",
      "j_mp_seltzer",
      "j_mp_shipoftheseus_sandbox",
      "j_mp_starfruit_sandbox",
      "j_mp_ticket",
      "j_mp_trafficlight_sandbox",
      "j_mp_turtle_bean",
      "j_mp_tuxedo_sandbox",
      "j_mp_warlock_sandbox",
      "j_mp_werewolf_sandbox",
    },
    ["reworked_tags"] = {
      "tag_mp_gambling_sandbox",
      "tag_mp_investment_sandbox",
      "tag_mp_juggle_sandbox",
    },
    ["reworked_vouchers"] = {},
    ["spectral_banned_enhancements"] = {},
    ["standard"] = true,
  },
  ["experimental"] = {
    ["_has_functions"] = {
      ["create_info_menu"] = true,
      ["force_lobby_options"] = true,
      ["is_disabled"] = true,
    },
    ["banned_blinds"] = {},
    ["banned_consumables"] = {
      "c_justice",
    },
    ["banned_enhancements"] = {
      "m_glass",
    },
    ["banned_jokers"] = {
      "j_mp_speedrun",
    },
    ["banned_silent"] = {
      "c_ouija",
      "j_bloodstone",
      "j_hanging_chad",
      "j_idol",
      "j_selzer",
      "j_ticket",
      "j_todo_list",
    },
    ["banned_tags"] = {},
    ["banned_vouchers"] = {},
    ["forced_gamemode"] = "gamemode_mp_attrition",
    ["key"] = "experimental",
    ["multiplayer_content"] = true,
    ["reworked_blinds"] = {},
    ["reworked_consumables"] = {
      "c_mp_ouija_standard",
    },
    ["reworked_enhancements"] = {
      "m_glass",
      "m_gold",
    },
    ["reworked_jokers"] = {
      "j_mp_bloodstone",
      "j_mp_hanging_chad",
      "j_mp_idol_rare",
      "j_mp_seltzer",
      "j_mp_ticket_experimental",
      "j_mp_todo_list",
    },
    ["reworked_tags"] = {},
    ["reworked_vouchers"] = {},
    ["spectral_banned_enhancements"] = {},
    ["standard"] = true,
  },
  ["experimental_legacy"] = {
    ["_has_functions"] = {
      ["create_info_menu"] = true,
      ["force_lobby_options"] = true,
      ["is_disabled"] = true,
    },
    ["banned_blinds"] = {},
    ["banned_consumables"] = {
      "c_justice",
      "c_mp_asteroid",
    },
    ["banned_enhancements"] = {},
    ["banned_jokers"] = {},
    ["banned_silent"] = {
      "j_hanging_chad",
      "j_mp_conjoined_joker",
      "j_mp_defensive_joker",
      "j_mp_pacifist",
      "j_mp_penny_pincher",
      "j_mp_pizza",
      "j_mp_skip_off",
      "j_mp_speedrun",
      "j_mp_taxes",
    },
    ["banned_tags"] = {},
    ["banned_vouchers"] = {},
    ["forced_gamemode"] = "gamemode_mp_attrition",
    ["forced_lobby_options"] = true,
    ["key"] = "experimental_legacy",
    ["multiplayer_content"] = true,
    ["reworked_blinds"] = {},
    ["reworked_consumables"] = {},
    ["reworked_enhancements"] = {
      "m_glass",
    },
    ["reworked_jokers"] = {
      "j_mp_hanging_chad",
      "j_mp_lets_go_gambling",
    },
    ["reworked_tags"] = {},
    ["reworked_vouchers"] = {},
    ["spectral_banned_enhancements"] = {},
  },
  ["legacy_ranked"] = {
    ["_has_functions"] = {
      ["create_info_menu"] = true,
      ["force_lobby_options"] = true,
      ["is_disabled"] = true,
    },
    ["banned_blinds"] = {},
    ["banned_consumables"] = {},
    ["banned_enhancements"] = {},
    ["banned_jokers"] = {},
    ["banned_silent"] = {},
    ["banned_tags"] = {},
    ["banned_vouchers"] = {},
    ["forced_gamemode"] = "gamemode_mp_attrition",
    ["forced_lobby_options"] = true,
    ["key"] = "legacy_ranked",
    ["multiplayer_content"] = false,
    ["reworked_blinds"] = {},
    ["reworked_consumables"] = {},
    ["reworked_enhancements"] = {
      "m_glass",
    },
    ["reworked_jokers"] = {},
    ["reworked_tags"] = {},
    ["reworked_vouchers"] = {},
    ["spectral_banned_enhancements"] = {},
  },
  ["majorleague"] = {
    ["_has_functions"] = {
      ["create_info_menu"] = true,
      ["force_lobby_options"] = true,
      ["is_disabled"] = true,
    },
    ["banned_blinds"] = {},
    ["banned_consumables"] = {},
    ["banned_enhancements"] = {},
    ["banned_jokers"] = {},
    ["banned_silent"] = {
      "j_bloodstone",
    },
    ["banned_tags"] = {},
    ["banned_vouchers"] = {},
    ["forced_gamemode"] = "gamemode_mp_attrition",
    ["forced_lobby_options"] = true,
    ["key"] = "majorleague",
    ["multiplayer_content"] = false,
    ["reworked_blinds"] = {},
    ["reworked_consumables"] = {},
    ["reworked_enhancements"] = {},
    ["reworked_jokers"] = {
      "j_mp_bloodstone",
    },
    ["reworked_tags"] = {},
    ["reworked_vouchers"] = {},
  },
  ["minorleague"] = {
    ["_has_functions"] = {
      ["create_info_menu"] = true,
      ["force_lobby_options"] = true,
      ["is_disabled"] = true,
    },
    ["banned_blinds"] = {},
    ["banned_consumables"] = {},
    ["banned_enhancements"] = {},
    ["banned_jokers"] = {},
    ["banned_tags"] = {},
    ["banned_vouchers"] = {},
    ["forced_gamemode"] = "gamemode_mp_attrition",
    ["forced_lobby_options"] = true,
    ["key"] = "minorleague",
    ["multiplayer_content"] = false,
    ["reworked_blinds"] = {},
    ["reworked_consumables"] = {},
    ["reworked_enhancements"] = {},
    ["reworked_jokers"] = {},
    ["reworked_tags"] = {},
    ["reworked_vouchers"] = {},
  },
  ["sandbox"] = {
    ["_has_functions"] = {
      ["create_info_menu"] = true,
      ["force_lobby_options"] = true,
      ["is_disabled"] = true,
    },
    ["banned_blinds"] = {},
    ["banned_consumables"] = {
      "c_ectoplasm",
      "c_ouija",
    },
    ["banned_enhancements"] = {},
    ["banned_jokers"] = {
      "j_hanging_chad",
    },
    ["banned_silent"] = {
      "j_baseball",
      "j_castle",
      "j_hit_the_road",
      "j_idol",
      "j_mail",
      "j_misprint",
      "j_square",
      "j_steel_joker",
      "j_throwback",
      "j_ticket",
      "j_vampire",
    },
    ["banned_tags"] = {
      "tag_investment",
      "tag_juggle",
      "tag_rare",
    },
    ["banned_vouchers"] = {},
    ["forced_lobby_options"] = true,
    ["key"] = "sandbox",
    ["multiplayer_content"] = true,
    ["reworked_blinds"] = {},
    ["reworked_consumables"] = {
      "c_mp_ectoplasm_sandbox",
      "c_mp_ouija_standard",
    },
    ["reworked_enhancements"] = {
      "m_glass",
    },
    ["reworked_jokers"] = {
      "j_mp_alloy_sandbox",
      "j_mp_ambrosia_sandbox",
      "j_mp_bobby_sandbox",
      "j_mp_candynecklace_sandbox",
      "j_mp_chainlightning_sandbox",
      "j_mp_clowncar_sandbox",
      "j_mp_clowncollege_sandbox",
      "j_mp_couponsheet_sandbox",
      "j_mp_doublerainbow_sandbox",
      "j_mp_error_sandbox_1",
      "j_mp_error_sandbox_10",
      "j_mp_error_sandbox_11",
      "j_mp_error_sandbox_12",
      "j_mp_error_sandbox_13",
      "j_mp_error_sandbox_14",
      "j_mp_error_sandbox_2",
      "j_mp_error_sandbox_3",
      "j_mp_error_sandbox_4",
      "j_mp_error_sandbox_5",
      "j_mp_error_sandbox_6",
      "j_mp_error_sandbox_7",
      "j_mp_error_sandbox_8",
      "j_mp_error_sandbox_9",
      "j_mp_espresso_sandbox",
      "j_mp_farmer_sandbox",
      "j_mp_forklift_sandbox",
      "j_mp_gofish_sandbox",
      "j_mp_hanging_chad",
      "j_mp_hoarder_sandbox",
      "j_mp_idol_sandbox_collector",
      "j_mp_idol_sandbox_zealot",
      "j_mp_jokalisa_sandbox",
      "j_mp_jokeroftheyear_sandbox",
      "j_mp_lucky7_sandbox",
      "j_mp_montehaul_sandbox",
      "j_mp_pocketaces_sandbox",
      "j_mp_pyromancer_sandbox",
      "j_mp_shipoftheseus_sandbox",
      "j_mp_starfruit_sandbox",
      "j_mp_trafficlight_sandbox",
      "j_mp_tuxedo_sandbox",
      "j_mp_warlock_sandbox",
      "j_mp_werewolf_sandbox",
    },
    ["reworked_tags"] = {
      "tag_mp_gambling_sandbox",
      "tag_mp_investment_sandbox",
      "tag_mp_juggle_sandbox",
    },
    ["reworked_vouchers"] = {},
    ["spectral_banned_enhancements"] = {},
  },
  ["smallworld"] = {
    ["_has_functions"] = {
      ["create_info_menu"] = true,
      ["force_lobby_options"] = true,
      ["is_disabled"] = true,
    },
    ["banned_blinds"] = {},
    ["banned_consumables"] = {
      "c_justice",
    },
    ["banned_enhancements"] = {},
    ["banned_jokers"] = {},
    ["banned_silent"] = {
      "c_ouija",
      "j_bloodstone",
      "j_hanging_chad",
      "j_selzer",
      "j_ticket",
      "j_turtle_bean",
    },
    ["banned_tags"] = {},
    ["banned_vouchers"] = {},
    ["key"] = "smallworld",
    ["multiplayer_content"] = true,
    ["reworked_blinds"] = {},
    ["reworked_consumables"] = {
      "c_mp_ouija_standard",
    },
    ["reworked_enhancements"] = {
      "m_glass",
    },
    ["reworked_jokers"] = {
      "j_mp_bloodstone",
      "j_mp_hanging_chad",
      "j_mp_seltzer",
      "j_mp_ticket",
      "j_mp_turtle_bean",
    },
    ["reworked_tags"] = {},
    ["reworked_vouchers"] = {},
    ["spectral_banned_enhancements"] = {},
    ["standard"] = true,
  },
  ["speedlatro"] = {
    ["_has_functions"] = {
      ["create_info_menu"] = true,
      ["force_lobby_options"] = true,
      ["is_disabled"] = true,
    },
    ["banned_blinds"] = {},
    ["banned_consumables"] = {
      "c_justice",
    },
    ["banned_enhancements"] = {},
    ["banned_jokers"] = {},
    ["banned_silent"] = {
      "c_ouija",
      "j_bloodstone",
      "j_hanging_chad",
      "j_selzer",
      "j_ticket",
      "j_turtle_bean",
    },
    ["banned_tags"] = {},
    ["banned_vouchers"] = {},
    ["forced_gamemode"] = "gamemode_mp_attrition",
    ["key"] = "speedlatro",
    ["multiplayer_content"] = true,
    ["reworked_blinds"] = {},
    ["reworked_consumables"] = {
      "c_mp_ouija_standard",
    },
    ["reworked_enhancements"] = {
      "m_glass",
    },
    ["reworked_jokers"] = {
      "j_mp_bloodstone",
      "j_mp_hanging_chad",
      "j_mp_seltzer",
      "j_mp_ticket",
      "j_mp_turtle_bean",
    },
    ["reworked_tags"] = {},
    ["reworked_vouchers"] = {},
    ["spectral_banned_enhancements"] = {},
    ["standard"] = true,
  },
  ["standard_ranked"] = {
    ["_has_functions"] = {
      ["create_info_menu"] = true,
      ["force_lobby_options"] = true,
      ["is_disabled"] = true,
    },
    ["banned_blinds"] = {},
    ["banned_consumables"] = {
      "c_justice",
    },
    ["banned_enhancements"] = {},
    ["banned_jokers"] = {},
    ["banned_silent"] = {
      "c_ouija",
      "j_bloodstone",
      "j_hanging_chad",
      "j_selzer",
      "j_ticket",
      "j_turtle_bean",
    },
    ["banned_tags"] = {},
    ["banned_vouchers"] = {},
    ["forced_gamemode"] = "gamemode_mp_attrition",
    ["forced_lobby_options"] = true,
    ["key"] = "standard_ranked",
    ["multiplayer_content"] = true,
    ["reworked_blinds"] = {},
    ["reworked_consumables"] = {
      "c_mp_ouija_standard",
    },
    ["reworked_enhancements"] = {
      "m_glass",
    },
    ["reworked_jokers"] = {
      "j_mp_bloodstone",
      "j_mp_hanging_chad",
      "j_mp_seltzer",
      "j_mp_ticket",
      "j_mp_turtle_bean",
    },
    ["reworked_tags"] = {},
    ["reworked_vouchers"] = {},
    ["spectral_banned_enhancements"] = {},
    ["standard"] = true,
  },
  ["traditional"] = {
    ["_has_functions"] = {
      ["create_info_menu"] = true,
      ["force_lobby_options"] = true,
      ["is_disabled"] = true,
    },
    ["banned_blinds"] = {},
    ["banned_consumables"] = {
      "c_justice",
    },
    ["banned_enhancements"] = {},
    ["banned_jokers"] = {
      "j_mp_conjoined_joker",
      "j_mp_speedrun",
    },
    ["banned_silent"] = {
      "c_ouija",
      "j_bloodstone",
      "j_hanging_chad",
      "j_selzer",
      "j_ticket",
      "j_turtle_bean",
    },
    ["banned_tags"] = {},
    ["banned_vouchers"] = {},
    ["key"] = "traditional",
    ["multiplayer_content"] = true,
    ["reworked_blinds"] = {},
    ["reworked_consumables"] = {
      "c_mp_ouija_standard",
    },
    ["reworked_enhancements"] = {
      "m_glass",
    },
    ["reworked_jokers"] = {
      "j_mp_bloodstone",
      "j_mp_hanging_chad",
      "j_mp_seltzer",
      "j_mp_ticket",
      "j_mp_turtle_bean",
    },
    ["reworked_tags"] = {},
    ["reworked_vouchers"] = {},
    ["spectral_banned_enhancements"] = {},
    ["standard"] = true,
  },
  ["vanilla"] = {
    ["_has_functions"] = {
      ["create_info_menu"] = true,
      ["force_lobby_options"] = true,
      ["is_disabled"] = true,
    },
    ["banned_blinds"] = {},
    ["banned_consumables"] = {},
    ["banned_enhancements"] = {},
    ["banned_jokers"] = {},
    ["banned_tags"] = {},
    ["banned_vouchers"] = {},
    ["key"] = "vanilla",
    ["multiplayer_content"] = false,
    ["reworked_blinds"] = {},
    ["reworked_consumables"] = {},
    ["reworked_enhancements"] = {},
    ["reworked_jokers"] = {},
    ["reworked_tags"] = {},
    ["reworked_vouchers"] = {},
  },
}
